-- begin FIRSTPROJECT_ADRESSES
alter table FIRSTPROJECT_ADRESSES add constraint FK_FIRSTPROJECT_ADRESSES_ON_CONTRAGENT foreign key (CONTRAGENT_ID) references FIRSTPROJECT_CONTRAGENTS(ID)^
create index IDX_FIRSTPROJECT_ADRESSES_ON_CONTRAGENT on FIRSTPROJECT_ADRESSES (CONTRAGENT_ID)^
-- end FIRSTPROJECT_ADRESSES
-- begin FIRSTPROJECT_CONTRAGENTS
alter table FIRSTPROJECT_CONTRAGENTS add constraint FK_FIRSTPROJECT_CONTRAGENTS_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table FIRSTPROJECT_CONTRAGENTS add constraint FK_FIRSTPROJECT_CONTRAGENTS_ON_CONTACT_INFO foreign key (CONTACT_INFO_ID) references FIRSTPROJECT_CONTACT_INFO(ID)^
create index IDX_FIRSTPROJECT_CONTRAGENTS_ON_IMAGE on FIRSTPROJECT_CONTRAGENTS (IMAGE_ID)^
create index IDX_FIRSTPROJECT_CONTRAGENTS_ON_CONTACT_INFO on FIRSTPROJECT_CONTRAGENTS (CONTACT_INFO_ID)^
-- end FIRSTPROJECT_CONTRAGENTS
-- begin FIRSTPROJECT_ROLES
alter table FIRSTPROJECT_ROLES add constraint FK_FIRSTPROJECT_ROLES_ON_CONTRAGENTS foreign key (CONTRAGENTS_ID) references FIRSTPROJECT_CONTRAGENTS(ID)^
create index IDX_FIRSTPROJECT_ROLES_ON_CONTRAGENTS on FIRSTPROJECT_ROLES (CONTRAGENTS_ID)^
-- end FIRSTPROJECT_ROLES
-- begin FIRSTPROJECT_TEAM
alter table FIRSTPROJECT_TEAM add constraint FK_FIRSTPROJECT_TEAM_ON_CONTAGENTS foreign key (CONTAGENTS_ID) references FIRSTPROJECT_CONTRAGENTS(ID)^
create index IDX_FIRSTPROJECT_TEAM_ON_CONTAGENTS on FIRSTPROJECT_TEAM (CONTAGENTS_ID)^
-- end FIRSTPROJECT_TEAM
