alter table FIRSTPROJECT_CONTRAGENTS add constraint FK_FIRSTPROJECT_CONTRAGENTS_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
create index IDX_FIRSTPROJECT_CONTRAGENTS_ON_IMAGE on FIRSTPROJECT_CONTRAGENTS (IMAGE_ID);
