alter table FIRSTPROJECT_TEAM add constraint FK_FIRSTPROJECT_TEAM_ON_CONTAGENTS foreign key (CONTAGENTS_ID) references FIRSTPROJECT_CONTRAGENTS(ID);
create index IDX_FIRSTPROJECT_TEAM_ON_CONTAGENTS on FIRSTPROJECT_TEAM (CONTAGENTS_ID);
